services:
  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tbl-test
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - APP_PORT=3000
      - DB_CLIENT=pg
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=tbl-test
    depends_on:
      - postgres
    networks:
      - app-network
    command: sh -c " echo 'Waiting for 5 seconds for PostgreSQL to be ready...'; sleep 5; npm run migrate:up && npm run start:dev "
  adminer:
    image: adminer
    ports:
      - "8080:8080"
    networks:
      - app-network
volumes:
  postgres_data:


networks:
  app-network:
    driver: bridge
